USE Abhishek;

ALTER TABLE users ADD CONSTRAINT unique_email UNIQUE (email);
ALTER TABLE users DROP COLUMN new_id;
ALTER TABLE users MODIFY COLUMN id INT NOT NULL PRIMARY KEY;
ALTER TABLE users ADD CONSTRAINT chk_dob CHECK (date_of_birth > '2000-01-01');
ALTER TABLE users ADD COLUMN is_active BOOLEAN;
ALTER TABLE users ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users ADD new_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE users AUTO_INCREMENT = 1000;
ALTER TABLE addresses DROP FOREIGN KEY fk_user;
ALTER TABLE users DROP INDEX email;

SHOW CREATE TABLE users;

DESC users;
