USE Abhishek;

SELECT *FROM users ORDER BY date_of_birth DESC;
SELECT *FROM users ORDER BY salary DESC LIMIT 4;
SELECT *FROM users ORDER BY id DESC LIMIT 3;
SELECT *FROM users ORDER BY id DESC LIMIT 2 OFFSET 3;
